name: bloc_login
description: Login Flow in Flutter using the Bloc library.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  bloc: ^6.0.0
  formz: ^0.2.0
  equatable: ^1.2.3
  flutter_bloc: ^6.0.0
  
  user_repository:
    path: packages/user_repository
  authentication_repository:
    path: packages/authentication_repository

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^4.1.1
  bloc_test: ^7.0.0

flutter:
  uses-material-design: true